/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Check for new versions over the network? */
#define CHECK_VERSION 

/* Use the Debian upgrade procedure instead of DACTs internal one */
/* #undef DACT_DEBIAN_UPGRADE_PROC */

/* Debug */
/* #undef DEBUG */

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Have bzdopen() ? */
/* #undef HAVE_BZDOPEN */

/* Define to 1 if you have the <bzlib.h> header file. */
/* #undef HAVE_BZLIB_H */

/* Have more versatile compress2() ? */
#define HAVE_COMPRESS2 

/* Have random device? */
#define HAVE_DEV_URANDOM 

/* Define to 1 if you have the <dirent.h> header file. */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Have dlopen()? */
#define HAVE_DLOPEN 1

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if fseeko (and presumably ftello) exists and is declared. */
#define HAVE_FSEEKO 1

/* Have gethostbyname() */
#define HAVE_GETHOSTBYNAME 

/* Define to 1 if you have the `getopt' function. */
#define HAVE_GETOPT 1

/* Define to 1 if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* Define to 1 if you have the `getpass' function. */
#define HAVE_GETPASS 1

/* Have gzdopen() ? */
#define HAVE_GZDOPEN 

/* Have inet_addr() */
/* #undef HAVE_INET_ADDR */

/* Have inet_aton() */
#define HAVE_INET_ATON 

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Something */
/* #undef HAVE_LIBBZ2 */

/* Also something */
/* #undef HAVE_LIBLZO */

/* Something */
/* #undef HAVE_LIBMCRYPT */

/* Have libwsock32 */
/* #undef HAVE_LIBWSOCK32 */

/* Something */
#define HAVE_LIBZ 

/* Define to 1 if you have the <lzo1x.h> header file. */
/* #undef HAVE_LZO1X_H */

/* Define to 1 if you have the <lzo1y.h> header file. */
/* #undef HAVE_LZO1Y_H */

/* Define to 1 if you have the <lzo2a.h> header file. */
/* #undef HAVE_LZO2A_H */

/* Define to 1 if you have the <lzoconf.h> header file. */
/* #undef HAVE_LZOCONF_H */

/* Define to 1 if you have the <mcrypt.h> header file. */
/* #undef HAVE_MCRYPT_H */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mkstemp' function. */
#define HAVE_MKSTEMP 1

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Have BZ2_ prefixed to all bzip2 symbols? */
/* #undef HAVE_NEW_BZ2 */

/* Have BZ2_bzdopen() ? */
/* #undef HAVE_NEW_BZDOPEN */

/* Do not have BZ2_ prefixed to all bzip2 symbols? */
/* #undef HAVE_OLD_BZ2 */

/* Have socket() */
#define HAVE_SOCKET 

/* Define to 1 if you have the <stdarg.h> header file. */
#define HAVE_STDARG_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strsep' function. */
#define HAVE_STRSEP 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/utsname.h> header file. */
#define HAVE_SYS_UTSNAME_H 1

/* Define to 1 if you have the <sys/wait.h> header file. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the `uname' function. */
#define HAVE_UNAME 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <windowsx.h> header file. */
/* #undef HAVE_WINDOWSX_H */

/* Define to 1 if you have the <windows.h> header file. */
/* #undef HAVE_WINDOWS_H */

/* Define to 1 if you have the <winsock2.h> header file. */
/* #undef HAVE_WINSOCK2_H */

/* Define to 1 if you have the <zlib.h> header file. */
#define HAVE_ZLIB_H 1

/* Disable all network support */
/* #undef NO_NETWORK */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 8

/* The size of a `long long', as computed by sizeof. */
#define SIZEOF_LONG_LONG 8

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Enable use of dynamically loadable modules? */
#define USE_MODULES 1

/* Number of bits in a file offset, on hosts where this is settable. */
/* #undef _FILE_OFFSET_BITS */

/* Define to 1 to make fseeko visible on some hosts (e.g. glibc 2.2). */
/* #undef _LARGEFILE_SOURCE */

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `signed short' if <sys/types.h> does not define. */
/* #undef int16_t */

/* Define to `signed short' if <sys/types.h> does not define. */
/* #undef int32_t */

/* Define to `signed short' if <sys/types.h> does not define. */
/* #undef int64_t */

/* Define to `long' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define to `unsigned int' if <sys/types.h> does not define. */
/* #undef uint */

/* Define to `unsigned short' if <sys/types.h> does not define. */
/* #undef uint16_t */

/* Define to `unsigned short' if <sys/types.h> does not define. */
/* #undef uint32_t */

/* Define to `unsigned short' if <sys/types.h> does not define. */
/* #undef uint64_t */
